// NILTASK professional shell enhancer
// Presentation layer only. Existing handlers, permissions and data flows remain authoritative.
(function () {
  'use strict';

  const CSS = `
  @media(min-width:769px){
    #nfaNavigationRail{width:76px;min-width:76px;height:100%;display:flex;flex-direction:column;align-items:center;padding:16px 10px 14px;gap:12px;background:linear-gradient(180deg,#1f2437,#252b42);border-right:1px solid rgba(255,255,255,.055);box-shadow:8px 0 28px rgba(31,36,55,.08);z-index:35}
    .nfa-rail-logo{width:46px;height:46px;border-radius:15px;display:grid;place-items:center;color:#fff;font-size:21px;font-weight:700;background:linear-gradient(135deg,#5a57d8,#8275f1);box-shadow:0 12px 28px rgba(90,87,216,.36),inset 0 1px 0 rgba(255,255,255,.25)}
    .nfa-rail-items{display:flex;flex-direction:column;align-items:center;gap:7px;width:100%}.nfa-rail-spacer{flex:1}
    .nfa-rail-button{width:54px;min-height:52px;border:0;border-radius:14px;background:transparent;color:#b8bfd3;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;cursor:pointer;transition:.18s}.nfa-rail-button i{font-size:20px}.nfa-rail-button span{font-size:9px;font-weight:700}.nfa-rail-button:hover{color:#fff;background:rgba(255,255,255,.08);transform:translateY(-1px)}.nfa-rail-button.is-active{color:#fff;background:linear-gradient(135deg,#5a57d8,#756aeb);box-shadow:0 10px 23px rgba(90,87,216,.28)}
    #leftSidebar.nfa-left-sidebar{background:rgba(255,255,255,.98)!important;box-shadow:4px 0 24px rgba(31,36,55,.035)!important}.nfa-left-sidebar>div:first-child{padding:15px 14px 11px!important;background:linear-gradient(180deg,#fff,#fafaff)!important}.nfa-product-label{font-size:9px!important;letter-spacing:.17em!important;color:#5a57d8!important;margin-bottom:7px!important}.nfa-school-name{display:block!important;width:100%!important;padding:12px 14px!important;margin:0 0 11px!important;font-size:17px!important;border-radius:15px!important;color:#fff!important;background:linear-gradient(145deg,#6662e4,#514ecb 52%,#413eae)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.3),inset 0 -3px 0 rgba(34,31,112,.3),0 12px 24px rgba(70,67,180,.23)!important;text-shadow:0 2px 3px rgba(25,23,90,.34)!important;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
    .nfa-conversation-list{padding:7px 8px 12px!important}.nfa-conversation-list .channel-item{border-radius:13px!important;margin:3px 0!important}.nfa-conversation-list .channel-item:hover{background:#f0f1ff!important;transform:translateX(2px)}.nfa-user-strip{background:linear-gradient(180deg,#fbfbfe,#f6f7fb)!important;padding:10px 11px!important}
    .nfa-chat-area>div:first-child{min-height:70px;padding:12px 18px!important;background:rgba(255,255,255,.96)!important;box-shadow:0 5px 20px rgba(31,36,55,.045)!important}.nfa-chat-area>div:last-child{background:rgba(255,255,255,.97)!important;box-shadow:0 -5px 18px rgba(31,36,55,.035)!important}.nfa-legacy-module-button{display:none!important}
    #messagesContainer.nfa-messages{padding:22px 24px!important;background-color:#f7f8fc!important;background-image:radial-gradient(circle at 1px 1px,rgba(90,87,216,.055) 1px,transparent 0)!important;background-size:24px 24px!important}
    #rightSidebar.nfa-task-sidebar{background:rgba(255,255,255,.985)!important;box-shadow:-7px 0 28px rgba(31,36,55,.045)!important}
  }
  .nfa-message-shell{max-width:920px!important;margin:0 auto!important;padding:0 14px 28px!important}.nfa-message-row{margin:14px 0!important;display:flex!important;width:100%!important}.nfa-message-row.row-sent{justify-content:flex-end!important}.nfa-message-row.row-rcvd{justify-content:flex-start!important}
  .nfa-message-bubble{position:relative!important;width:min(680px,76%)!important;max-width:76%!important;padding:0!important;border:1px solid #e3e7f0!important;border-radius:18px!important;background:#fff!important;box-shadow:0 10px 28px rgba(31,36,55,.07)!important;overflow:visible!important}.row-sent .nfa-message-bubble{border-left:4px solid #5a57d8!important}.row-rcvd .nfa-message-bubble{border-left:4px solid #e99a2f!important}
  .nfa-message-bubble .b-header{display:grid!important;grid-template-columns:38px minmax(0,1fr) auto auto!important;align-items:center!important;gap:10px!important;padding:12px 13px 10px!important;border-bottom:1px solid #edf0f5!important}.nfa-message-bubble .b-avatar{width:34px!important;height:34px!important;border-radius:11px!important}.nfa-message-bubble .b-avatar img{border-radius:11px!important}.nfa-message-bubble .b-text{padding:15px 16px 13px!important;font-size:16px!important;line-height:1.62!important;max-width:68ch!important}.nfa-message-bubble .b-actions{display:flex!important;gap:8px!important;flex-wrap:wrap!important;padding:9px 14px 12px!important;border-top:1px solid #edf0f5!important}.nfa-message-bubble .act-btn{display:inline-flex!important;align-items:center!important;gap:5px!important;min-height:32px!important;padding:7px 10px!important;border-radius:9px!important}.nfa-message-bubble .bubble-dropdown{right:8px!important;top:44px!important;min-width:190px!important;padding:6px!important;border:1px solid #e3e6ef!important;border-radius:14px!important;background:#fff!important;box-shadow:0 18px 48px rgba(31,36,55,.18)!important;z-index:70!important}.nfa-message-bubble .dd-item{width:100%!important;min-height:40px!important;display:flex!important;align-items:center!important;gap:10px!important;padding:9px 11px!important;border-radius:9px!important;font-size:12px!important;font-weight:600!important}.nfa-message-bubble .replies-wrap{margin:0 12px 12px!important;padding:10px!important;border:1px solid #e7e9f2!important;border-radius:13px!important;background:#f8f9fd!important}
  .nfa-message-composer{padding:10px 16px 14px!important;background:rgba(255,255,255,.98)!important}.nfa-message-composer>div:last-child{border:1px solid #dfe3ec!important;border-radius:16px!important;background:#fbfcfe!important;box-shadow:0 8px 24px rgba(31,36,55,.06)!important}
  @media(max-width:1120px) and (min-width:769px){#nfaNavigationRail{width:68px;min-width:68px}.nfa-rail-button{width:48px}.nfa-rail-button span{display:none}.nfa-message-bubble{width:86%!important;max-width:86%!important}}
  @media(max-width:768px){#nfaNavigationRail{display:none!important}.nfa-message-shell{padding:0 8px 90px!important}.nfa-message-bubble{width:94%!important;max-width:94%!important}.nfa-message-bubble .b-text{max-width:none!important}.nfa-message-bubble .bubble-dropdown{position:fixed!important;left:10px!important;right:10px!important;top:auto!important;bottom:calc(72px + env(safe-area-inset-bottom))!important;min-width:0!important;border-radius:18px!important;z-index:11050!important}}
  `;

  const MODULES=[
    {selector:"[onclick*=\"openTopPanel('scheduled')\"]",key:'schedule',label:'Schedule',icon:'ti-calendar-time'},
    {selector:"[onclick*=\"openTopPanel('reminders')\"]",key:'reminders',label:'Reminders',icon:'ti-alarm'},
    {selector:"[onclick*=\"openTopPanel('bookmarks')\"]",key:'bookmarks',label:'Bookmarks',icon:'ti-bookmark'},
    {selector:'[onclick*="openActivityFeed"]',key:'activity',label:'Activity',icon:'ti-activity'},
    {selector:'[onclick*="toggleRightSidebar"]',key:'tasks',label:'Tasks',icon:'ti-checkbox'}
  ];

  function loadRefinements(){
    if(!document.getElementById('nfa-refinement-css')){const l=document.createElement('link');l.id='nfa-refinement-css';l.rel='stylesheet';l.href='./css/professional-refinements.css?v=1';document.head.appendChild(l)}
    if(!document.getElementById('nfa-refinement-js')){const s=document.createElement('script');s.id='nfa-refinement-js';s.src='./js/professional-refinements.js?v=1';s.defer=true;document.head.appendChild(s)}
  }
  function ensureStyles(){if(!document.getElementById('nfa-shell-style')){const s=document.createElement('style');s.id='nfa-shell-style';s.textContent=CSS;document.head.appendChild(s)}loadRefinements()}
  function showMessages(){window.closeActivityFeed?.();const left=document.getElementById('leftSidebar');if(left&&getComputedStyle(left).display==='none')window.toggleLeftSidebar?.();setActiveRail('messages')}
  const RAIL_ITEMS=[{key:'messages',label:'Messages',icon:'ti-messages',action:showMessages},{key:'tasks',label:'Tasks',icon:'ti-checkbox',action:()=>window.toggleRightSidebar?.()},{key:'activity',label:'Activity',icon:'ti-activity',action:()=>window.openActivityFeed?.()},{key:'notifications',label:'Notifications',icon:'ti-bell',action:()=>window.openTopPanel?.('alerts')},{key:'schedule',label:'Schedule',icon:'ti-calendar-time',action:()=>window.openTopPanel?.('scheduled')}];
  function setActiveRail(key){document.querySelectorAll('.nfa-rail-button').forEach(b=>b.classList.toggle('is-active',b.dataset.module===key))}
  function makeButton(item){const b=document.createElement('button');b.type='button';b.className='nfa-rail-button';b.dataset.module=item.key;b.title=item.label;b.setAttribute('aria-label',item.label);b.innerHTML=`<i class="ti ${item.icon}"></i><span>${item.label}</span>`;b.onclick=()=>{item.action();setActiveRail(item.key)};return b}
  function ensureRail(){if(innerWidth<=768)return;const left=document.getElementById('leftSidebar'),row=left?.parentElement;if(!left||!row||document.getElementById('nfaNavigationRail'))return;const rail=document.createElement('nav');rail.id='nfaNavigationRail';rail.setAttribute('aria-label','Main modules');const logo=document.createElement('div');logo.className='nfa-rail-logo';logo.textContent='N';rail.appendChild(logo);const items=document.createElement('div');items.className='nfa-rail-items';RAIL_ITEMS.forEach(i=>items.appendChild(makeButton(i)));rail.append(items,Object.assign(document.createElement('div'),{className:'nfa-rail-spacer'}),makeButton({key:'settings',label:'Settings',icon:'ti-settings',action:()=>window.openSettings?.()}));row.insertBefore(rail,left);setActiveRail('messages')}
  function schoolBrand(){const left=document.getElementById('leftSidebar'),header=left?.firstElementChild;if(!header)return;const name=window.currentSchoolName||'My School';let el=document.getElementById('nfaSchoolName');if(!el){el=document.createElement('div');el.id='nfaSchoolName';el.className='nfa-school-name';header.prepend(el)}el.textContent=name;el.title=name;[...header.querySelectorAll('div')].find(x=>x.textContent?.trim()==='Noted For Action')?.classList.add('nfa-product-label')}
  function enhance(){ensureStyles();document.getElementById('leftSidebar')?.classList.add('nfa-left-sidebar');document.getElementById('rightSidebar')?.classList.add('nfa-task-sidebar');document.querySelector('.chat-area')?.classList.add('nfa-chat-area');document.getElementById('messagesContainer')?.classList.add('nfa-messages');document.getElementById('chatsList')?.classList.add('nfa-conversation-list');[...document.getElementById('leftSidebar')?.children||[]].at(-1)?.classList.add('nfa-user-strip');ensureRail();schoolBrand();MODULES.forEach(m=>document.querySelectorAll(m.selector).forEach(b=>b.classList.add('nfa-legacy-module-button')));document.getElementById('chatShellContainer')?.classList.add('nfa-message-shell');document.querySelectorAll('#chatShellContainer [id^="row-"]').forEach(r=>{r.classList.add('nfa-message-row');r.querySelector('.bubble')?.classList.add('nfa-message-bubble')});document.querySelector('.nfa-chat-area>div:last-child')?.classList.add('nfa-message-composer')}
  let pending=false;function schedule(){if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;enhance()})}
  new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('resize',schedule,{passive:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
})();