// NILTASK professional shell enhancer
// Presentation layer only. Existing handlers, permissions and data flows remain authoritative.
(function () {
  'use strict';

  const SHELL_CSS = `
    @media (min-width:769px){
      #nfaNavigationRail{width:76px;min-width:76px;height:100%;display:flex;flex-direction:column;align-items:center;padding:16px 10px 14px;gap:12px;background:linear-gradient(180deg,#1f2437 0%,#252b42 100%);border-right:1px solid rgba(255,255,255,.055);box-shadow:8px 0 28px rgba(31,36,55,.08);z-index:35}
      .nfa-rail-logo{width:46px;height:46px;border-radius:15px;display:grid;place-items:center;color:#fff;font-size:21px;font-weight:700;background:linear-gradient(135deg,#5a57d8,#8275f1);box-shadow:0 12px 28px rgba(90,87,216,.36),inset 0 1px 0 rgba(255,255,255,.25)}
      .nfa-rail-items{display:flex;flex-direction:column;align-items:center;gap:7px;width:100%}
      .nfa-rail-spacer{flex:1}
      .nfa-rail-button{width:54px;min-height:52px;border:0;border-radius:14px;background:transparent;color:#b8bfd3;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;cursor:pointer;transition:.18s ease}
      .nfa-rail-button i{font-size:20px;line-height:1}.nfa-rail-button span{font-size:9px;font-weight:700;letter-spacing:.01em}
      .nfa-rail-button:hover{color:#fff;background:rgba(255,255,255,.08);transform:translateY(-1px)}
      .nfa-rail-button.is-active{color:#fff;background:linear-gradient(135deg,#5a57d8,#756aeb);box-shadow:0 10px 23px rgba(90,87,216,.28)}
      #leftSidebar.nfa-left-sidebar{border-radius:0!important;background:rgba(255,255,255,.98)!important;box-shadow:4px 0 24px rgba(31,36,55,.035)!important}
      .nfa-left-sidebar>div:first-child{padding:15px 14px 11px!important;background:linear-gradient(180deg,#fff 0%,#fafaff 100%)!important}
      .nfa-product-label{font-size:9px!important;letter-spacing:.17em!important;color:#5a57d8!important;margin-bottom:7px!important}
      .nfa-school-name{display:block!important;width:100%!important;padding:12px 14px!important;margin:0 0 11px!important;font-size:17px!important;border-radius:15px!important;color:#fff!important;background:linear-gradient(145deg,#6662e4 0%,#514ecb 52%,#413eae 100%)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.3),inset 0 -3px 0 rgba(34,31,112,.3),0 12px 24px rgba(70,67,180,.23)!important;text-shadow:0 2px 3px rgba(25,23,90,.34)!important;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
      .nfa-conversation-list{padding:7px 8px 12px!important}.nfa-conversation-list .channel-item,.nfa-conversation-list>[class*="cursor"]{border-radius:13px!important;margin:3px 0!important;transition:.16s ease!important}.nfa-conversation-list .channel-item:hover,.nfa-conversation-list>[class*="cursor"]:hover{background:#f0f1ff!important;transform:translateX(2px)}
      .nfa-sidebar-search-wrap{padding:9px 10px!important;background:#fafbfe!important}.nfa-sidebar-search{border-radius:12px!important;background:#f5f6fa!important;border:1px solid #e6e9f1!important}.nfa-user-strip{background:linear-gradient(180deg,#fbfbfe,#f6f7fb)!important;padding:10px 11px!important}
      .nfa-chat-area>div:first-child{min-height:70px;padding:12px 18px!important;background:rgba(255,255,255,.96)!important;box-shadow:0 5px 20px rgba(31,36,55,.045)!important}#roomTitleDisplay{font-size:18px!important;font-weight:700!important;letter-spacing:-.015em!important}
      #messagesContainer.nfa-messages{padding:22px 24px!important;background-color:#f7f8fc!important;background-image:radial-gradient(circle at 1px 1px,rgba(90,87,216,.055) 1px,transparent 0)!important;background-size:24px 24px!important}
      .nfa-chat-area>div:last-child{background:rgba(255,255,255,.97)!important;box-shadow:0 -5px 18px rgba(31,36,55,.035)!important}
      #rightSidebar.nfa-task-sidebar{background:rgba(255,255,255,.985)!important;box-shadow:-7px 0 28px rgba(31,36,55,.045)!important}#rightSidebar .jira-card{margin:10px!important;border-radius:16px!important}
      .nfa-legacy-module-button{display:none!important}.topbar-icon-btn{border-radius:11px!important;padding:6px 8px!important}.topbar-icon-btn span{font-size:9px!important}
    }
    @media (max-width:1120px) and (min-width:769px){#nfaNavigationRail{width:68px;min-width:68px}.nfa-rail-button{width:48px}.nfa-rail-button span{display:none}}
    @media (max-width:768px){#nfaNavigationRail{display:none!important}}
  `;

  const MESSAGE_CSS = `
    .nfa-message-shell{max-width:980px!important;margin:0 auto!important;padding:0 14px 28px!important}
    .nfa-message-row{margin:14px 0!important;display:flex!important;width:100%!important}
    .nfa-message-row.row-sent{justify-content:flex-end!important}.nfa-message-row.row-rcvd{justify-content:flex-start!important}
    .nfa-message-bubble{position:relative!important;width:min(720px,78%)!important;max-width:78%!important;padding:0!important;border:1px solid #e3e7f0!important;border-radius:18px!important;background:#fff!important;box-shadow:0 10px 28px rgba(31,36,55,.07)!important;overflow:visible!important;transition:transform .18s ease,border-color .18s ease,box-shadow .18s ease!important}
    .row-sent .nfa-message-bubble{border-left:4px solid #5a57d8!important}.row-rcvd .nfa-message-bubble{border-left:4px solid #e99a2f!important}
    .nfa-message-bubble:hover{transform:translateY(-1px)!important;border-color:#cbcaff!important;box-shadow:0 16px 38px rgba(31,36,55,.11)!important}
    .nfa-message-bubble .b-header{display:grid!important;grid-template-columns:38px minmax(0,1fr) auto auto!important;align-items:center!important;gap:10px!important;padding:12px 13px 10px!important;border-bottom:1px solid #edf0f5!important;background:linear-gradient(180deg,#fff,#fcfcff)!important;border-radius:16px 16px 0 0!important}
    .nfa-message-bubble .b-avatar{width:34px!important;height:34px!important;border-radius:11px!important;box-shadow:0 4px 12px rgba(31,36,55,.12)!important}
    .nfa-message-bubble .b-avatar img{border-radius:11px!important}.nfa-message-bubble .b-name{font-size:13px!important;font-weight:700!important;color:#20283a!important;min-width:0!important}.nfa-message-bubble .b-role{font-size:10px!important;font-weight:600!important;color:#746fe3!important}.nfa-message-bubble .b-time{font-size:10px!important;color:#8a92a5!important;white-space:nowrap!important}.nfa-message-bubble .b-tick{color:#625ee1!important;font-weight:700!important}
    .nfa-message-bubble .dot-btn{width:32px!important;height:32px!important;display:grid!important;place-items:center!important;border:1px solid transparent!important;border-radius:10px!important;color:#7b8498!important;background:transparent!important}.nfa-message-bubble .dot-btn:hover{color:#504dcc!important;background:#efefff!important;border-color:#dadaff!important}
    .nfa-message-bubble .b-text{padding:15px 16px 13px!important;font-size:16px!important;line-height:1.62!important;color:#242b3d!important;overflow-wrap:anywhere!important}.nfa-message-bubble .b-text p{margin:0 0 6px!important}.nfa-message-bubble .b-text p:last-child{margin-bottom:0!important}
    .nfa-message-bubble .b-footer{display:flex!important;align-items:center!important;gap:6px!important;flex-wrap:wrap!important;padding:5px 14px 8px!important;min-height:36px!important}.nfa-message-bubble .e-add{width:30px!important;height:30px!important;border:1px solid #e2e5ee!important;border-radius:10px!important;background:#f8f9fc!important;color:#737c91!important}.nfa-message-bubble .e-add:hover{background:#efefff!important;color:#5652d3!important;border-color:#d5d4ff!important}
    .nfa-message-bubble .e-chip{min-height:28px!important;padding:4px 8px!important;border:1px solid #dedff0!important;border-radius:999px!important;background:#f7f7ff!important;box-shadow:none!important}.nfa-message-bubble .e-chip.mine{border-color:#aaa8f3!important;background:#efefff!important}
    .nfa-message-bubble .b-actions{display:flex!important;align-items:center!important;gap:5px!important;flex-wrap:wrap!important;padding:8px 12px 11px!important;border-top:1px solid #edf0f5!important}.nfa-message-bubble .act-btn{min-height:32px!important;padding:6px 9px!important;border:0!important;border-radius:9px!important;background:transparent!important;color:#70798e!important;font-size:11px!important;font-weight:600!important}.nfa-message-bubble .act-btn:hover{background:#eff0ff!important;color:#504dcc!important}.nfa-message-bubble .act-btn.bookmarked{background:#fff7e8!important;color:#a26409!important}
    .nfa-message-bubble .bubble-dropdown{right:8px!important;top:44px!important;min-width:190px!important;padding:6px!important;border:1px solid #e3e6ef!important;border-radius:14px!important;background:#fff!important;box-shadow:0 18px 48px rgba(31,36,55,.18)!important;z-index:70!important}.nfa-message-bubble .dd-item{width:100%!important;min-height:40px!important;display:flex!important;align-items:center!important;gap:10px!important;padding:9px 11px!important;border:0!important;border-radius:9px!important;background:transparent!important;color:#333b4f!important;font-size:12px!important;font-weight:600!important;text-align:left!important}.nfa-message-bubble .dd-item i{width:18px!important;font-size:17px!important;color:#6965db!important}.nfa-message-bubble .dd-item:hover{background:#f1f1ff!important;color:#4946be!important}.nfa-message-bubble .dd-item.danger{color:#c9445b!important}.nfa-message-bubble .dd-item.danger i{color:#d34d62!important}.nfa-message-bubble .dd-item.danger:hover{background:#fff0f2!important}
    .nfa-message-bubble .replies-wrap{margin:0 12px 12px!important;padding:10px!important;border:1px solid #e7e9f2!important;border-radius:13px!important;background:#f8f9fd!important}.nfa-message-bubble .replies-label{font-size:10px!important;font-weight:700!important;color:#5a57d8!important;text-transform:uppercase!important;letter-spacing:.08em!important;margin-bottom:6px!important}.nfa-message-bubble .reply-item{display:grid!important;grid-template-columns:24px minmax(0,1fr)!important;gap:8px!important;padding:8px 4px!important;border-top:1px solid #eceef4!important}.nfa-message-bubble .reply-item:first-of-type{border-top:0!important}.nfa-message-bubble .reply-num{width:22px!important;height:22px!important;border-radius:8px!important;background:#5a57d8!important;color:#fff!important;display:grid!important;place-items:center!important;font-size:9px!important}.nfa-message-bubble .reply-name{font-size:11px!important;font-weight:700!important}.nfa-message-bubble .reply-role,.nfa-message-bubble .reply-time{font-size:9px!important;color:#8991a3!important}.nfa-message-bubble .reply-text{font-size:12px!important;line-height:1.5!important;margin-top:3px!important}
    .nfa-message-bubble .file-card{width:min(100%,360px)!important;max-width:100%!important;border-radius:13px!important;padding:10px 12px!important;box-shadow:0 5px 16px rgba(31,36,55,.06)!important}.nfa-message-bubble img{max-width:100%!important}
    .nfa-message-composer{padding:10px 16px 14px!important;background:rgba(255,255,255,.98)!important}.nfa-message-composer>div:last-child{border:1px solid #dfe3ec!important;border-radius:16px!important;background:#fbfcfe!important;box-shadow:0 8px 24px rgba(31,36,55,.06)!important;overflow:visible!important}.nfa-message-composer .ql-toolbar{border:0!important;border-bottom:1px solid #e9ecf3!important;background:#f8f9fc!important;border-radius:15px 15px 0 0!important}.nfa-message-composer .ql-container{border:0!important}.nfa-message-composer .ql-editor{min-height:52px!important;padding:13px 14px!important;font-size:16px!important}.nfa-message-composer button[onclick*="sendMessage"],.nfa-message-composer button[title*="Send"]{border-radius:12px!important;background:linear-gradient(135deg,#5a57d8,#756aeb)!important;box-shadow:0 8px 18px rgba(90,87,216,.3)!important}
    @media(max-width:1100px) and (min-width:769px){.nfa-message-bubble{width:min(650px,88%)!important;max-width:88%!important}}
    @media(max-width:768px){.nfa-message-shell{padding:0 8px 90px!important}.nfa-message-row{margin:9px 0!important}.nfa-message-bubble{width:92%!important;max-width:92%!important;border-radius:16px!important}.nfa-message-bubble .b-header{grid-template-columns:32px minmax(0,1fr) auto auto!important;padding:10px!important}.nfa-message-bubble .b-avatar{width:30px!important;height:30px!important}.nfa-message-bubble .b-text{padding:12px 13px!important;font-size:15.5px!important}.nfa-message-bubble .bubble-dropdown{position:fixed!important;left:10px!important;right:10px!important;top:auto!important;bottom:calc(72px + env(safe-area-inset-bottom))!important;min-width:0!important;border-radius:18px!important;padding:8px!important;z-index:11050!important}.nfa-message-bubble .dd-item{min-height:46px!important;font-size:14px!important}.nfa-message-composer{padding:8px 9px calc(9px + env(safe-area-inset-bottom))!important}}
  `;

  const MODULES = [
    { selector: '[onclick*="openTopPanel(\'scheduled\')"]', key: 'schedule', label: 'Schedule', icon: 'ti-calendar-time' },
    { selector: '[onclick*="openTopPanel(\'reminders\')"]', key: 'reminders', label: 'Reminders', icon: 'ti-alarm' },
    { selector: '[onclick*="openTopPanel(\'bookmarks\')"]', key: 'bookmarks', label: 'Bookmarks', icon: 'ti-bookmark' },
    { selector: '[onclick*="openActivityFeed"]', key: 'activity', label: 'Activity', icon: 'ti-activity' },
    { selector: '[onclick*="toggleRightSidebar"]', key: 'tasks', label: 'Tasks', icon: 'ti-checkbox' }
  ];

  const RAIL_ITEMS = [
    { key: 'messages', label: 'Messages', icon: 'ti-messages', action: showMessages },
    { key: 'tasks', label: 'Tasks', icon: 'ti-checkbox', action: () => window.toggleRightSidebar?.() },
    { key: 'activity', label: 'Activity', icon: 'ti-activity', action: () => window.openActivityFeed?.() },
    { key: 'notifications', label: 'Notifications', icon: 'ti-bell', action: () => window.openTopPanel?.('alerts') },
    { key: 'schedule', label: 'Schedule', icon: 'ti-calendar-time', action: () => window.openTopPanel?.('scheduled') }
  ];

  function ensureStyles(){
    if(!document.getElementById('nfa-visible-shell-style')){const s=document.createElement('style');s.id='nfa-visible-shell-style';s.textContent=SHELL_CSS;document.head.appendChild(s)}
    if(!document.getElementById('nfa-message-style')){const s=document.createElement('style');s.id='nfa-message-style';s.textContent=MESSAGE_CSS;document.head.appendChild(s)}
  }
  function showMessages(){window.closeActivityFeed?.();const left=document.getElementById('leftSidebar');if(left&&getComputedStyle(left).display==='none')window.toggleLeftSidebar?.();document.getElementById('messagesContainer')?.focus?.({preventScroll:true});setActiveRail('messages')}
  function setActiveRail(key){document.querySelectorAll('.nfa-rail-button').forEach(b=>{const active=b.dataset.module===key;b.classList.toggle('is-active',active);active?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')})}
  function createRailButton(item){const b=document.createElement('button');b.type='button';b.className='nfa-rail-button';b.dataset.module=item.key;b.setAttribute('aria-label',item.label);b.title=item.label;b.innerHTML=`<i class="ti ${item.icon}" aria-hidden="true"></i><span>${item.label}</span>`;b.addEventListener('click',()=>{item.action();setActiveRail(item.key)});return b}
  function ensureNavigationRail(){if(window.innerWidth<=768)return;const left=document.getElementById('leftSidebar'),appRow=left?.parentElement;if(!left||!appRow||document.getElementById('nfaNavigationRail'))return;const rail=document.createElement('nav');rail.id='nfaNavigationRail';rail.setAttribute('aria-label','Main modules');const logo=document.createElement('div');logo.className='nfa-rail-logo';logo.textContent='N';logo.title='NILTASK';rail.appendChild(logo);const items=document.createElement('div');items.className='nfa-rail-items';RAIL_ITEMS.forEach(i=>items.appendChild(createRailButton(i)));rail.appendChild(items);const spacer=document.createElement('div');spacer.className='nfa-rail-spacer';rail.appendChild(spacer);rail.appendChild(createRailButton({key:'settings',label:'Settings',icon:'ti-settings',action:()=>window.openSettings?.()}));appRow.insertBefore(rail,left);setActiveRail('messages')}
  function enhanceSchoolBrand(){const left=document.getElementById('leftSidebar'),header=left?.firstElementChild;if(!left||!header)return;const schoolName=window.currentSchoolName||'My School';let school=document.getElementById('nfaSchoolName');if(!school){school=document.createElement('div');school.id='nfaSchoolName';school.className='nfa-school-name';const p=[...header.querySelectorAll('div')].find(el=>el.textContent?.trim()==='Noted For Action');if(p?.nextSibling)header.insertBefore(school,p.nextSibling);else header.prepend(school)}school.textContent=schoolName;school.title=schoolName;const label=[...header.querySelectorAll('div')].find(el=>el.textContent?.trim()==='Noted For Action');label?.classList.add('nfa-product-label')}
  function enhanceConversationPanel(){const left=document.getElementById('leftSidebar');if(!left)return;left.querySelector('#chatsList')?.classList.add('nfa-conversation-list');left.querySelector('#sidebarSearchWrap')?.classList.add('nfa-sidebar-search-wrap');left.querySelector('#sidebarSearch')?.classList.add('nfa-sidebar-search');[...left.children].at(-1)?.classList.add('nfa-user-strip')}
  function enhanceModuleButtons(){MODULES.forEach(m=>document.querySelectorAll(m.selector).forEach(b=>{b.classList.add('nfa-module-button','nfa-legacy-module-button');b.dataset.module=m.key;b.setAttribute('aria-label',m.label);const icon=b.querySelector('i');if(icon){[...icon.classList].filter(c=>c==='fa-solid'||c.startsWith('fa-')||c.startsWith('ti-')).forEach(c=>icon.classList.remove(c));icon.classList.add('ti',m.icon)}const label=b.querySelector('span');if(label)label.textContent=m.label}))}
  function enhanceMessages(){const shell=document.getElementById('chatShellContainer');shell?.classList.add('nfa-message-shell');document.querySelectorAll('#chatShellContainer [id^="row-"]').forEach(row=>{row.classList.add('nfa-message-row');row.querySelector('.bubble')?.classList.add('nfa-message-bubble')});const composer=document.querySelector('.nfa-chat-area>div:last-child');composer?.classList.add('nfa-message-composer')}
  function enhanceShell(){ensureStyles();document.documentElement.classList.add('nfa-professional-ui');document.getElementById('root')?.classList.add('nfa-app-root');document.getElementById('leftSidebar')?.classList.add('nfa-left-sidebar');document.getElementById('rightSidebar')?.classList.add('nfa-task-sidebar');document.querySelector('.chat-area')?.classList.add('nfa-chat-area');document.getElementById('messagesContainer')?.classList.add('nfa-messages');document.getElementById('tasksPanel')?.classList.add('nfa-task-panel');ensureNavigationRail();enhanceSchoolBrand();enhanceConversationPanel();enhanceModuleButtons();enhanceMessages()}
  let scheduled=false;function scheduleEnhance(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;enhanceShell()})}
  const observer=new MutationObserver(scheduleEnhance);observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('resize',scheduleEnhance,{passive:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scheduleEnhance,{once:true});else scheduleEnhance();
})();